module.exports = function (node) {
    let block = {
        'address': 'address',
        'area': 'area',
        'article': 'article',
        'aside': 'aside',
        'audio': 'audio',
        'base': 'base',
        'blockquote': 'blockquote',
        // 'body': 'body',
        'button': 'button',
        'canvas': 'canvas',
        'caption': 'caption',
        'center': 'center',
        'col': 'col',
        'colgroup': 'colgroup',
        'command': 'command',
        'datalist': 'datalist',
        'dd': 'dd',
        'details': 'details',
        'dir': 'dir',
        'div': 'div',
        'dl': 'dl',
        'dt': 'dt',
        'embed': 'embed',
        'fieldset': 'fieldset',
        'figcaption': 'figcaption',
        'figure': 'figure',
        'footer': 'footer',
        'form': 'form',
        'frame': 'frame',
        'frameset': 'frameset',
        'h1': 'h1',
        'h2': 'h2',
        'h3': 'h3',
        'h4': 'h4',
        'h5': 'h5',
        'h6': 'h6',
        // 'head': 'head',
        'header': 'header',
        'hgroup': 'hgroup',
        'hr': 'hr',
        // 'html': 'html',
        'input': 'input',
        'isindex': 'isindex',
        'keygen': 'keygen',
        'label': 'label',
        'legend': 'legend',
        'li': 'li',
        'link': 'link',
        'menu': 'menu',
        'meta': 'meta',
        'meter': 'meter',
        'nav': 'nav',
        'noframes': 'noframes',
        'noscript': 'noscript',
        'ol': 'ol',
        'optgroup': 'optgroup',
        'option': 'option',
        'output': 'output',
        'p': 'p',
        'test': 'test',
        'param': 'param',
        'pre': 'pre',
        'progress': 'progress',
        'ruby': 'ruby',
        'section': 'section',
        'select': 'select',
        'source': 'source',
        'style': 'style',
        'summary': 'summary',
        'table': 'table',
        'tbody': 'tbody',
        'td': 'td',
        'textarea': 'textarea',
        'tfoot': 'tfoot',
        'th': 'th',
        'thead': 'thead',
        'title': 'title',
        'tr': 'tr',
        'track': 'track',
        'ul': 'ul',
        'video': 'video'
    }
    if (node in block) {
        return true
    } else {
        return false
    }
}

//block

//address      
// area
// article
// aside
// audio
// base
// blockquote
// body
// button
// canvas
// caption
// center
// col
// colgroup
// command
// datalist
// dd
// details
// dir
// div
// dl
// dt
// embed
// fieldset
// figcaption
// figure
// footer
// form
// frame
// frameset
// h1
// h2
// h3
// h4
// h5
// h6
// head
// header
// hgroup
// hr
// html
// input
// isindex
// keygen
// label
// legend
// li
// link
// menu
// meta
// meter
// nav
// noframes
// noscript
// ol
// optgroup
// option
// output
// p
// param
// pre
// progress
// ruby
// section
// select
// source
// style
// summary
// table
// tbody
// td
// textarea
// tfoot
// th
// thead
// title
// tr
// track
// ul
// video


//inline

    // < a > 
    // <abbr>
    // <acronym>
    // <b>
    // <bdo>
    // <big>
    // <br>
    // <button>
    // <cite>
    // <code>
    // <dfn>
    // <em>
    // <i>
    // <img>
    // <input>
    // <kbd>
    // <label>
    // <map>
    // <object>
    // <output>
    // <q>
    // <samp>
    // <script>
    // <select>
    // <small>
    // <span>
    // <strong>
    // <sub>
    // <sup>
    // <textarea>
    // <time>
    // <tt>
    // <var>